# Generated by Django 5.0.4 on 2024-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='portfolio',
            new_name='portfolio_item',
        ),
    ]
