# Generated by Django 5.0.6 on 2024-05-15 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_portfolio_comment_portfolio_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='likes',
            field=models.ManyToManyField(related_name='portfolio_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
